/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HSlugRouteImport } from './routes/h.$slug'
import { Route as HackathonsNewRouteImport } from './routes/hackathons.new'
import { Route as JudgeSlugRouteImport } from './routes/judge.$slug'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as AppHackathonsIdRouteImport } from './routes/app.hackathons.$id'
import { Route as HSlugTeamsTeamIdRouteImport } from './routes/h.$slug.teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugRoute = HSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsNewRoute = HackathonsNewRouteImport.update({
  id: '/hackathons/new',
  path: '/hackathons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeSlugRoute = JudgeSlugRouteImport.update({
  id: '/judge/$slug',
  path: '/judge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHackathonsIdRoute = AppHackathonsIdRouteImport.update({
  id: '/app/hackathons/$id',
  path: '/app/hackathons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugTeamsTeamIdRoute = HSlugTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => HSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/h/$slug': typeof HSlugRouteWithChildren
  '/hackathons/new': typeof HackathonsNewRoute
  '/judge/$slug': typeof JudgeSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/app/hackathons/$id': typeof AppHackathonsIdRoute
  '/h/$slug/teams/$teamId': typeof HSlugTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/h/$slug': typeof HSlugRouteWithChildren
  '/hackathons/new': typeof HackathonsNewRoute
  '/judge/$slug': typeof JudgeSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/app/hackathons/$id': typeof AppHackathonsIdRoute
  '/h/$slug/teams/$teamId': typeof HSlugTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/h/$slug': typeof HSlugRouteWithChildren
  '/hackathons/new': typeof HackathonsNewRoute
  '/judge/$slug': typeof JudgeSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/app/hackathons/$id': typeof AppHackathonsIdRoute
  '/h/$slug/teams/$teamId': typeof HSlugTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/h/$slug'
    | '/hackathons/new'
    | '/judge/$slug'
    | '/team/$slug'
    | '/app/hackathons/$id'
    | '/h/$slug/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/h/$slug'
    | '/hackathons/new'
    | '/judge/$slug'
    | '/team/$slug'
    | '/app/hackathons/$id'
    | '/h/$slug/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/h/$slug'
    | '/hackathons/new'
    | '/judge/$slug'
    | '/team/$slug'
    | '/app/hackathons/$id'
    | '/h/$slug/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  HSlugRoute: typeof HSlugRouteWithChildren
  HackathonsNewRoute: typeof HackathonsNewRoute
  JudgeSlugRoute: typeof JudgeSlugRoute
  TeamSlugRoute: typeof TeamSlugRoute
  AppHackathonsIdRoute: typeof AppHackathonsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug': {
      id: '/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof HSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/new': {
      id: '/hackathons/new'
      path: '/hackathons/new'
      fullPath: '/hackathons/new'
      preLoaderRoute: typeof HackathonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/$slug': {
      id: '/judge/$slug'
      path: '/judge/$slug'
      fullPath: '/judge/$slug'
      preLoaderRoute: typeof JudgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/hackathons/$id': {
      id: '/app/hackathons/$id'
      path: '/app/hackathons/$id'
      fullPath: '/app/hackathons/$id'
      preLoaderRoute: typeof AppHackathonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug/teams/$teamId': {
      id: '/h/$slug/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/h/$slug/teams/$teamId'
      preLoaderRoute: typeof HSlugTeamsTeamIdRouteImport
      parentRoute: typeof HSlugRoute
    }
  }
}

interface HSlugRouteChildren {
  HSlugTeamsTeamIdRoute: typeof HSlugTeamsTeamIdRoute
}

const HSlugRouteChildren: HSlugRouteChildren = {
  HSlugTeamsTeamIdRoute: HSlugTeamsTeamIdRoute,
}

const HSlugRouteWithChildren = HSlugRoute._addFileChildren(HSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  HSlugRoute: HSlugRouteWithChildren,
  HackathonsNewRoute: HackathonsNewRoute,
  JudgeSlugRoute: JudgeSlugRoute,
  TeamSlugRoute: TeamSlugRoute,
  AppHackathonsIdRoute: AppHackathonsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
